"""领域模型：System / Module / SystemVersion / Sandbox / Run / Evaluation / Comparison。"""

from eddplatform.domain.models import (  # noqa: F401
    Case,
    CaseResult,
    Comparison,
    ContextField,
    Dataset,
    Environment,
    EvalResult,
    EvalStatus,
    Evaluation,
    EvaluatorDef,
    EvaluatorKind,
    EvaluatorScope,
    IsolationLevel,
    MetricDelta,
    Module,
    OutputType,
    RunRecord,
    RunStatus,
    RunType,
    SandboxConfig,
    System,
    SystemVersion,
    VersionStatus,
)
